// Generated by scripts/find-word-video-replacements.ts. Do not edit by hand.
export interface WorshipWordVideoReplacement { youtubeId: string; videoTitle: string }

export const WORSHIP_WORD_VIDEO_REPLACEMENTS: Record<string, WorshipWordVideoReplacement> = {
  "am2013-742a": {
    "youtubeId": "CFJvBwgmK_c",
    "videoTitle": "Oh, For a Thousand Tongues to Sing (Tune: Lyngham - 5vv) [with lyrics for congregations]"
  },
  "ws-77": {
    "youtubeId": "8rmCN-w__Gk",
    "videoTitle": "Just As I Am, Without One Plea (Tune: Woodworth - 4vv) [with lyrics for congregations]"
  },
  "sof1995-4": {
    "youtubeId": "MVQm8sijeTE",
    "videoTitle": "Alleluia (Lyric Video) Elevation Worship + Chandler Moore"
  },
  "am2013-370": {
    "youtubeId": "V6iOvsITOXc",
    "videoTitle": "Lord Have Mercy ([Kyrie] with Lyrics) - Lindell Cooley"
  },
  "am2013-804": {
    "youtubeId": "A3VuaVDwM24",
    "videoTitle": "There Is a Land of Pure Delight | Praise and Worship | English Christian Gospel Song with Lyrics"
  },
  "am2013-132": {
    "youtubeId": "0FyAY9fzcnU",
    "videoTitle": "O For a Heart to Praise My God (Tune: Abridge - 5vv) [with lyrics for congregations]"
  },
  "ws-61": {
    "youtubeId": "FiJYgC_6AFc",
    "videoTitle": "Crown Him With Many Crowns (Tune: Daidemata - 4vv) [with lyrics for congregations]"
  },
  "ws-81": {
    "youtubeId": "EbnQKie-yak",
    "videoTitle": "Nearer, My God, to Thee (Tune: Horbury - 4vv) [with lyrics for congregations]"
  },
  "ws-85": {
    "youtubeId": "TAyaXdvvbGU",
    "videoTitle": "What A Friend We Have In Jesus | Lyric Video | Lydia Walker | Acoustic Hymns with Lyrics"
  },
  "ws-93": {
    "youtubeId": "5dVGZFlfGOs",
    "videoTitle": "Eternal Father, Strong to Save (Tune: Melita - 4vv) [with lyrics for congregations)"
  },
  "am2013-418": {
    "youtubeId": "JwuDSw-9cUQ",
    "videoTitle": "Holy, Holy, Holy! Lord God Almighty - from The Hymns Project (Lyric Video)"
  },
  "am2013-679": {
    "youtubeId": "S8xDtj2nGfs",
    "videoTitle": "In Christ There Is No East or West - Tony Alonso (Lyrics)"
  },
  "am2013-765": {
    "youtubeId": "VSb7MZiu7T4",
    "videoTitle": "PRAISE TO THE LORD THE ALMIGHTY THE KING OF CREATION With Lyrics"
  },
  "am2013-810": {
    "youtubeId": "aJuqdIVH8VY",
    "videoTitle": "Thou Whose Almighty Word (Tune: Italian Hymn - 4vv) [with lyrics for congregations]"
  },
  "ws-92": {
    "youtubeId": "LgybEBy3rlM",
    "videoTitle": "Onward Christian Soldiers (Tune: St Gertrude - 5vv) [with lyrics for congregations]"
  },
  "am2013-45": {
    "youtubeId": "4WUWPxkMf3M",
    "videoTitle": "O Come, O Come Emmanuel - Ancient Worship Hymn of Hope (Orchestral Version & Lyrics)"
  },
  "am2013-378": {
    "youtubeId": "TAZrT8SVYBM",
    "videoTitle": "Break Thou The Bread of Life lyrics - hymn"
  },
  "sof1995-49": {
    "youtubeId": "TQ0Epw1rwbc",
    "videoTitle": "Blest be the tie that binds | lyric video"
  },
  "am2013-89a": {
    "youtubeId": "oTbxEtTktgE",
    "videoTitle": "While shepherds watched their flocks by night. Lyric video (StF 221)"
  },
  "am2013-117a": {
    "youtubeId": "sBc_paLAUAI",
    "videoTitle": "Come, Let Us To The Lord Our God - Hymn Lyrics & Music"
  },
  "am2013-231": {
    "youtubeId": "dzbmpAdss8Y",
    "videoTitle": "Look, Ye Saints, the Sight is Glorious - Hymn 279 - Lyric Video"
  },
  "am2013-232": {
    "youtubeId": "MOCLzH4rsjc",
    "videoTitle": "The Head That Once Was Crowned With Thorns(viopla section) - Hymn Lyrics & Music"
  },
  "am2013-324a": {
    "youtubeId": "In-MtdNjF44",
    "videoTitle": "Jesus Calls Us O'er the Tumult (lyrics)"
  },
  "am2013-394": {
    "youtubeId": "xt26v6lrk6k",
    "videoTitle": "HYMN: Tell out, my soul, the greatness of the Lord (Woodlands) with words/text/lyrics"
  },
  "am2013-480": {
    "youtubeId": "ld2rv9zOf58",
    "videoTitle": "God Be with You Till We Meet Again - Lyrics - Old Hymns of Faith"
  },
  "am2013-718": {
    "youtubeId": "uKziFYjaS7c",
    "videoTitle": "Lord, Speak to Me That I May Speak - PIANO and LYRICS"
  },
  "am2013-821": {
    "youtubeId": "BT_QUgWnxEI",
    "videoTitle": "032 SDA Hymn - When in Our Music God is Glorified (Singing w/ Lyrics)"
  },
  "sof1995-148": {
    "youtubeId": "K_U4v--Bc30",
    "videoTitle": "Guide Me, O Thou Great Jehovah - Lyrics"
  },
  "sof1995-543": {
    "youtubeId": "m8zHWUbVGRI",
    "videoTitle": "There Is a Name I Love to Hear | Classic Hymn with Lyrics"
  },
  "rs1900-131a": {
    "youtubeId": "slQ6MTJLU4I",
    "videoTitle": "Come, Ye Sinners, Poor and Needy • T4G Live IV [Official Lyric Video]"
  },
  "am2013-3": {
    "youtubeId": "0Nff3ZRVz9s",
    "videoTitle": "Father We Praise Thee Now the Night is Over Lyrics(Christe Sanctorum) #Trinity Hymns #Trinity Sunday"
  },
  "am2013-13": {
    "youtubeId": "pfmzBXjCH-c",
    "videoTitle": "At Even, Ere the Sun Was Set (Tune: At Even, Ere the Sun - 4vv) [with lyrics for congregations]"
  },
  "am2013-21": {
    "youtubeId": "4X-MZ_-WQs8",
    "videoTitle": "O Strength And Stay Upholding All Creation Lyrics (Strength And Stay) # Evening Hymns"
  },
  "am2013-119": {
    "youtubeId": "Yj91JOq2Xpw",
    "videoTitle": "Forgive Our Sins as We Forgive ('Koiné' - 4vv) [with lyrics for congregations]"
  },
  "am2013-130a": {
    "youtubeId": "hdp1DTu-XnE",
    "videoTitle": "MY SPIRIT LONGS FOR THEE Hymn Lyrics Words text trending sing along song music"
  },
  "am2013-131": {
    "youtubeId": "-wWVpafJX8A",
    "videoTitle": "O For A Closer Walk With God- Hymn - (With Lyrics)"
  },
  "am2013-145": {
    "youtubeId": "xMgXB3NGC2A",
    "videoTitle": "It is a thing most wonderful (Hymn with lyrics)"
  },
  "am2013-177": {
    "youtubeId": "bnFOFjVf4h8",
    "videoTitle": "AT THE CROSS HER STATION KEEPING Stabat Mater Lent Stations WAY of the Cross Lyrics Word sing along"
  },
  "am2013-198": {
    "youtubeId": "Nwl4uPwegxQ",
    "videoTitle": "At the Lamb's High Feast (Hymn with lyrics)"
  },
  "am2013-200a": {
    "youtubeId": "a2u_2yMfHLY",
    "videoTitle": "♫ Hymn | Christ the Lord is risen again! | with LYRICS"
  },
  "am2013-274": {
    "youtubeId": "4dvj-j_PvtA",
    "videoTitle": "Father i adore you (lyrics)"
  },
  "am2013-277a": {
    "youtubeId": "hRui-HKVYhQ",
    "videoTitle": "I Bind Unto Myself Today | St Patrick's Breast Plate | #hymn #organ #lyrics #stpatricksday"
  },
  "am2013-307": {
    "youtubeId": "LQDGUux5Pn4",
    "videoTitle": "Palms Of Glory Raiment Bright Lyrics (Palms Of Glory) # Festivals Of Martyrs And Other Holy Days"
  },
  "am2013-420a": {
    "youtubeId": "C7gWYh3BKBA",
    "videoTitle": "According To Thy Gracious Word (Lyrics)"
  },
  "am2013-684": {
    "youtubeId": "n7tX19p2R7s",
    "videoTitle": "Jerusalem, My Happy Home (Tune: Land of Rest - 3vv) [with lyrics for congregations]"
  },
  "am2013-704": {
    "youtubeId": "q2J6qCh9Y_U",
    "videoTitle": "009 SDA Hymn - Let All the World in Every Corner Sing (Singing w/ Lyrics)"
  },
  "am2013-781": {
    "youtubeId": "HLFBRQabnPc",
    "videoTitle": "Son Of God Eternal Saviour Lyrics (Bethany) # General Hymns"
  },
  "sof1995-393": {
    "youtubeId": "3Rifby1tVE8",
    "videoTitle": "MORNING HAS BROKEN - Cat Stevens (Lyrics)"
  },
  "sof1995-599": {
    "youtubeId": "WA_2RdqPOS0",
    "videoTitle": "When we Walk with the Lord lyrics"
  },
  "sof1995-605": {
    "youtubeId": "prVc9gF4cCY",
    "videoTitle": "150 SDA Hymn - Who Is He In Yonder Stall (Singing w/ Lyrics)"
  },
  "rs1900-62a": {
    "youtubeId": "8hnyQXhlhyA",
    "videoTitle": "I Will Lift Mine Eyes Lyrics by Terry Javier"
  },
  "rs1900-67a": {
    "youtubeId": "3h1GUkpkP2A",
    "videoTitle": "Love Divine All Loves Excelling - live with lyrics - 1080p"
  },
  "ws-76": {
    "youtubeId": "qmk9sfX_QPY",
    "videoTitle": "O Love that wilt not let me Go - Visual Worship with Lyrics !"
  },
  "ws-86": {
    "youtubeId": "wxcqtO8fYK0",
    "videoTitle": "Praise the Lord, Ye Heavens Adore Him (Tune: Austria - 3vv) [with lyrics for congregations]"
  },
  "curated-ws-118": {
    "youtubeId": "cRJZNosHJKU",
    "videoTitle": "Jesus, Name Above all Names - New Life Worship - Lyrics"
  },
  "am2013-20": {
    "youtubeId": "3AGUZZxPG4Y",
    "videoTitle": "O Gladsome Light, O Grace - acapella hymn with lyrics"
  },
  "am2013-142": {
    "youtubeId": "KszoCSY5g8k",
    "videoTitle": "Glory Be to Jesus (Tune: Wem in Leidenstagen - 5vv) [with lyrics for congregations]"
  },
  "am2013-148a": {
    "youtubeId": "EeWvtFl2oEI",
    "videoTitle": "O Dearest Lord, Thy Sacred Head | Lyric Video"
  },
  "am2013-181": {
    "youtubeId": "8kGxCpLty6E",
    "videoTitle": "O Sacred Head Surrounded | Classic Good Friday Hymn with Lyrics | Worship Song | Divine Hymns Elite"
  },
  "am2013-219": {
    "youtubeId": "9r9JK1sPB4A",
    "videoTitle": "This Joyful Eastertide (Tune: Vruchten - 3vv+refrain) [with lyrics for congregations]"
  },
  "am2013-223": {
    "youtubeId": "HdsvGbU7nV0",
    "videoTitle": "All Hail the Power of Jesus' Name - from The Hymns Project (Lyric Video)"
  },
  "am2013-242": {
    "youtubeId": "RBTaDL9khxA",
    "videoTitle": "\"Come Holy Spirit fall afresh on me\" - (Lyrics)"
  },
  "am2013-262": {
    "youtubeId": "cTas8HYKArk",
    "videoTitle": "Spirit Of Mercy Truth And Love Lyrics (Melcombe) # Whitsun Hymns"
  },
  "am2013-309": {
    "youtubeId": "IfNCvyc8Ce8",
    "videoTitle": "Soldiers Who Are Christs Below Lyrics (Orientis Partibus) # All Saints Day Hymns"
  },
  "am2013-317a": {
    "youtubeId": "aKHQ5GtHjt8",
    "videoTitle": "Hymn - Virgin Born, We Bow Before Thee - with words - Daniel Robert | Organist"
  },
  "am2013-383": {
    "youtubeId": "aJsk6XCM3mE",
    "videoTitle": "Lord, Thy Word Abideth - Hymn 179 - Lyric Video"
  },
  "am2013-441": {
    "youtubeId": "KpZFq61fofU",
    "videoTitle": "Draw Nigh And Take The Body Of The Lord Lyrics (Sancti Venite) # Communion Hymns"
  },
  "am2013-443": {
    "youtubeId": "tfX0mjFyInE",
    "videoTitle": "Father, We Thank Thee Who Hast Planted (with lyrics)"
  },
  "am2013-448a": {
    "youtubeId": "MhwN7u47vUo",
    "videoTitle": "Hymn - I Come With Joy, A Child Of God - with words - Daniel Roberts | Organist"
  },
  "am2013-471": {
    "youtubeId": "VzFFCc4NsU0",
    "videoTitle": "We Pray Thee, Heavenly Father (Tune: Meirionydd - 4vv) [with lyrics for congregations]"
  },
  "am2013-475": {
    "youtubeId": "GagsnW_DxCk",
    "videoTitle": "Forth in the Peace of Christ We Go (Tune: Deo Gracias - 5vv) [with lyrics for congregations]"
  },
  "am2013-491": {
    "youtubeId": "rZUsN1VaJL4",
    "videoTitle": "Go Into All The World ~ Lyric Video"
  },
  "am2013-603": {
    "youtubeId": "4YOPWEAeNJk",
    "videoTitle": "Bright The Vision That Delighted Lyrics (Laus Deo) # General Hymns"
  },
  "am2013-616": {
    "youtubeId": "ziZgfqrAI8E",
    "videoTitle": "Come O Thou Traveller Unknown Lyrics (Wrestling Jacob) # Mission Services"
  },
  "am2013-634a": {
    "youtubeId": "9MCEP09EyaM",
    "videoTitle": "Firmly I Believe And Truly (STAFFORD) | #hymn #organ #lyrics"
  },
  "am2013-656": {
    "youtubeId": "5868F4UCDJY",
    "videoTitle": "He's Got the Whole World in His Hands | Hymn with Lyrics | Dementia friendly"
  },
  "am2013-689a": {
    "youtubeId": "_KKoGjV5bqg",
    "videoTitle": "Jesus, Thou Joy of Loving Hearts - Christian Hymns ( Lyrics in description )"
  },
  "am2013-694": {
    "youtubeId": "g5w4AWYbiiA",
    "videoTitle": "JESUS LORD WE LOOK TO THEE Hymn Lyrics Words text trending sing along song music UMC 562 Methodist"
  },
  "am2013-697": {
    "youtubeId": "nDK4nBpHCLo",
    "videoTitle": "Join All The Glorious Names(Watt- long version) -  Old Hymn Lyrics & Music"
  },
  "am2013-703": {
    "youtubeId": "gIh3DfbTl9w",
    "videoTitle": "Lead, kindly light,amid the encircling gloom English Christian song with lyrics//WRC"
  },
  "am2013-719": {
    "youtubeId": "op17raOTXbk",
    "videoTitle": "Lord, the Light of Your Love is Shining (Shine Jesus Shine: 3vv+refrain) [lyrics for congregations]"
  },
  "am2013-726": {
    "youtubeId": "xdWpddjTsmw",
    "videoTitle": "May the Grace of Christ Our Saviour (Tune: Gott des Himmel - 2vv) [with lyrics for congregations]"
  },
  "am2013-733": {
    "youtubeId": "ENecZfjFUxU",
    "videoTitle": "My Life Flows On In Endless Song - Hymn Lyrics & Music"
  },
  "am2013-747": {
    "youtubeId": "XST5DCIHh6c",
    "videoTitle": "O God, You Search Me and You Know Me [with lyrics for congregations]"
  },
  "am2013-750": {
    "youtubeId": "wVtc-q1untc",
    "videoTitle": "O Lord of heaven, and earth, and sea (with lyrics) | By Christopher Wordsworth"
  },
  "am2013-755": {
    "youtubeId": "snAlrr6XPj0",
    "videoTitle": "Oft in Danger, Oft in Woe - Hymn 353 - Lyric Video"
  },
  "am2013-778a": {
    "youtubeId": "acY-x9GoFh0",
    "videoTitle": "Sing Praise to God Who Reigns Above Hymn [With Lyrics]"
  },
  "am2013-819": {
    "youtubeId": "rPdHkqfNjnw",
    "videoTitle": "To The Name Of Our Salvation Lyrics (Oriel) # Circumcision"
  },
  "sof1995-226": {
    "youtubeId": "IKF7sBxv1-o",
    "videoTitle": "I Love You Lord (and I Lift My Voice) Lyrics"
  },
  "sof1995-510": {
    "youtubeId": "BagH-zTfnsQ",
    "videoTitle": "Spirit of the Living God (worship video w/ lyrics)"
  },
  "sof1995-620": {
    "youtubeId": "TbCL6WtPsQg",
    "videoTitle": "YE SERVANTS OF GOD Hymn Lyrics Words text trending Methodist Sing Along Song 181"
  },
  "rs1900-132a": {
    "youtubeId": "vUV4_Zo-5nI",
    "videoTitle": "Tell Me the Old Old Story (with lyrics) | Beautiful classic hymn"
  },
  "rs1900-200": {
    "youtubeId": "xrxkx7vMhSM",
    "videoTitle": "Jesus Saves (We Have Heard The Joyful Sound - More Hymns of Praise and Worship) Lyric Video"
  },
  "rs1900-206a": {
    "youtubeId": "mXSyU_QYoP0",
    "videoTitle": "Behold the Amazing Gift of Love (Organ & Lyrics)"
  },
  "rs1900-279a": {
    "youtubeId": "ZoL_Bv8qvQc",
    "videoTitle": "283 SDA Hymn - O Jesus, Thou Art Standing (Singing w/ Lyrics)"
  },
  "rs1900-281a": {
    "youtubeId": "IvK02dokIcc",
    "videoTitle": "I Lay My Sins On Jesus ~ Eric Gilbert ~ lyric video"
  },
  "ws-29": {
    "youtubeId": "A0CDqG5STPM",
    "videoTitle": "How Deep The Father's Love For Us - Stuart Townend (Lyrics)"
  },
  "ws-50": {
    "youtubeId": "DrVJIdvIIq4",
    "videoTitle": "Be Still for the Presence of the Lord - David Evans - Lyrics"
  },
  "curated-ws-146": {
    "youtubeId": "9Y8zP34AhuU",
    "videoTitle": "Refiner's Fire (worship video w/ lyrics)"
  },
  "ws-78": {
    "youtubeId": "gQTajuWiIIU",
    "videoTitle": "Come Thou Fount every Blessing (Lyric Video) original composition of Rev.  Robert Robinson"
  },
  "curated-ws-101": {
    "youtubeId": "M3bsgoPjcg4",
    "videoTitle": "O Breath of Life, Come Sweeping Through Us (Tune: Spiritus Vitae - 4vv) [lyrics for congregations]"
  },
  "curated-ws-133": {
    "youtubeId": "1Zontyn2TjE",
    "videoTitle": "Majesty, Worship His Majesty [with lyrics for congregations]"
  },
  "am2013-29": {
    "youtubeId": "UT_opysbiQQ",
    "videoTitle": "Come Now, O Prince of Peace - Solo Piano with Lyrics"
  },
  "am2013-55": {
    "youtubeId": "sq3gEtTr5lQ",
    "videoTitle": "The King Shall Come When Morning Dawns | Advent Christian Hymn | John Brownlie | Choir w/ Lyrics"
  },
  "am2013-65": {
    "youtubeId": "2nIn8AwveCI",
    "videoTitle": "Good Christians All Rejoice | With Heart and Soul and Voice - Lyric Video"
  },
  "am2013-67": {
    "youtubeId": "y0jfaBOqvas",
    "videoTitle": "Holy Child Within the Manger with lyrics"
  },
  "am2013-97": {
    "youtubeId": "HifNQMgZS0Q",
    "videoTitle": "Christ Encounter - Bright and Morning Star (Lyric Video)"
  },
  "am2013-107": {
    "youtubeId": "_c07y6jul_8",
    "videoTitle": "Hymn - The Sinless One To Jordan Came - with words - Daniel Roberts | Organist"
  },
  "am2013-179": {
    "youtubeId": "U3kPZB9jPNE",
    "videoTitle": "Nature with open volume stands (with lyrics) | Christian Hymn of Worship by Isaac Watts"
  },
  "am2013-222": {
    "youtubeId": "SoHcfN9zxr0",
    "videoTitle": "You Shall Go Out with Joy (Tune: Trees of the Field) [with lyrics for congregations]"
  },
  "am2013-248": {
    "youtubeId": "5HuWRs3sQPA",
    "videoTitle": "680 SDA Hymn - Holy Spirit, Hear Us (Singing w/ Lyrics)"
  },
  "am2013-263": {
    "youtubeId": "EiRV5Z4qFAU",
    "videoTitle": "Spirit of the Living God, Fall Afresh on Me (Tune: Iverson - 2vv) [with lyrics for congregations]"
  },
  "am2013-271": {
    "youtubeId": "Pros0Yx4FGs",
    "videoTitle": "Life Worship - Father In Heaven (Official Lyric Video)"
  },
  "am2013-300": {
    "youtubeId": "0IRrqCCkkFo",
    "videoTitle": "To God Be the Glory (WITH LYRICS) 🙏 Powerful Christian Hymn of Worship & Praise"
  },
  "am2013-315": {
    "youtubeId": "tXmrNZKJ3-A",
    "videoTitle": "♫ Hymn | Sing we of the blessed Mother | with LYRICS"
  },
  "am2013-321": {
    "youtubeId": "z5jxGPCo7F0",
    "videoTitle": "Thou Art The Christ O Lord Lyrics (Cephas) # St. Peter The Apostle (June 29)"
  },
  "am2013-329": {
    "youtubeId": "NTbuZvDpAJQ",
    "videoTitle": "Hymn #325, vv. 1-3  Child Of Blessing Child of Promise by Ronald Cole-Turner (LYRICS)"
  },
  "am2013-390": {
    "youtubeId": "rkc4iE_jYRU",
    "videoTitle": "Praise (Thanks) to God Whose Word was Spoken (Tune: St Raphael- 4vv) [with lyrics for congregations]"
  },
  "am2013-403": {
    "youtubeId": "MiPoWNWB4FM",
    "videoTitle": "We Believe in God the Father-Graham Kendrick Lyric Video"
  },
  "am2013-415": {
    "youtubeId": "gKJEYRilKH0",
    "videoTitle": "GLORY, GLORY IN THE HIGHEST ( Divine Hymns ) Lyric Video"
  },
  "am2013-445": {
    "youtubeId": "NfJS0uwsLiY",
    "videoTitle": "God Is Here! As We Your People - Hymn Lyrics & Music"
  },
  "am2013-450": {
    "youtubeId": "yuIQuvsFD00",
    "videoTitle": "Jesus call us here to meet him. Lyric video (StF 28)"
  },
  "am2013-455": {
    "youtubeId": "SztDKmJ4OhM",
    "videoTitle": "My God And Is Thy Table Spread Lyrics (Rockingham) # Communion Hymns"
  },
  "am2013-456a": {
    "youtubeId": "v3gyVHoaRY4",
    "videoTitle": "404 SDA Hymnal - Now Let Us From This Table Rise (Singing w/ Lyrics)"
  },
  "am2013-457": {
    "youtubeId": "x4a0gtCDoAk",
    "videoTitle": "Now My Tongue The Mystery Telling Lyrics (Grafton Hymn Tune) #Communion Hymns"
  },
  "am2013-518": {
    "youtubeId": "xsMFP6ca-tw",
    "videoTitle": "O Christ, The Healer, We Have Come - Hymn Lyrics & Music"
  },
  "am2013-541": {
    "youtubeId": "IPgy8djUbs4",
    "videoTitle": "Lord of Beauty, Thine the Splendour (Tune: Regent Square - 4vv) [with lyrics for congregations]"
  },
  "am2013-542": {
    "youtubeId": "vqK1Y6fqPo4",
    "videoTitle": "097 SDA Hymn - Lord of the Boundless Curves of Space (Singing w/ Lyrics)"
  },
  "am2013-553a": {
    "youtubeId": "0Kckx4XNAmM",
    "videoTitle": "Touch the Earth Lightly with lyrics"
  },
  "am2013-559": {
    "youtubeId": "g3xu831YtrU",
    "videoTitle": "God of Freedom, God of Justice (Tune: Picardy - 3vv) [with lyrics for congregations]"
  },
  "am2013-590": {
    "youtubeId": "7ECU1pom5_c",
    "videoTitle": "As Jacob With Travel Was Weary One Day(Jacobs Ladder) - Hymn Lyrics & Music"
  },
  "am2013-608": {
    "youtubeId": "JdcT5pRY1fc",
    "videoTitle": "Christ is our Corner-stone (with lyrics) | Translated By John Chandler"
  },
  "am2013-715": {
    "youtubeId": "rUKyftvbs9Q",
    "videoTitle": "Lord For The Years Your Love Has Kept And Guided - Hymn Lyrics & Music"
  },
  "am2013-723": {
    "youtubeId": "vh6d7ebBaH0",
    "videoTitle": "Loved with Everlasting Love - Lyrics (Beautiful Christian Hymn) Song Video Cover"
  },
  "am2013-735": {
    "youtubeId": "GX82BuxiuFY",
    "videoTitle": "My Soul, There is a Country (Tune: Parry - 5vv) [with lyrics for congregations]"
  },
  "am2013-745": {
    "youtubeId": "RBz7vuJ2b1A",
    "videoTitle": "Doxology: Praise God From Whom All Blessings Flow (with lyrics)"
  },
  "am2013-762": {
    "youtubeId": "QT2Qf3CImqo",
    "videoTitle": "TSI • Praise the One Who Breaks the Darkness [LYRIC VIDEO] feat. Nathan Huse & Cara Berg"
  },
  "am2013-774": {
    "youtubeId": "iPBbpYlgN9c",
    "videoTitle": "Safe In The Shadow Of The Lord Song Lyrics Video - Divine Hymns"
  },
  "sof1995-175": {
    "youtubeId": "H3A8_I0DF38",
    "videoTitle": "Hosanna (Be Lifted Higher) Life Church Lyric"
  },
  "sof1995-220": {
    "youtubeId": "pNq22B2069g",
    "videoTitle": "I Know Not Why Gods Wondrous Grace (I Know Whom I Have Believed) SOF220 - song and lyrics"
  },
  "sof1995-242": {
    "youtubeId": "Lb6gNXKjeos",
    "videoTitle": "Be Glorified (In my life Lord) with singalong lyrics"
  },
  "sof1995-293": {
    "youtubeId": "1ykyhcnJoH8",
    "videoTitle": "Jesus Be The Name | Lyric Video | Elevation Worship (feat. Tiffany Hudson)"
  },
  "sof1995-338": {
    "youtubeId": "JXarxpi8ygg",
    "videoTitle": "Who Is This King of Glory? | Psalm 24 Worship Song (Lyric Video)"
  },
  "sof1995-385": {
    "youtubeId": "reXqZpYhbOU",
    "videoTitle": "Man of sorrows! What A Name with lyrics"
  },
  "sof1995-463": {
    "youtubeId": "1fnn6pjJT3A",
    "videoTitle": "Praise Him! Praise Him! Praise the Everlasting King 👑. (lyrics)"
  },
  "sof1995-468": {
    "youtubeId": "2QMafc3fDBA",
    "videoTitle": "Praise The Name Of Jesus/Praises by Maranatha! Music - Lyrics Video"
  },
  "sof1995-473": {
    "youtubeId": "8YCOfDtxs6Y",
    "videoTitle": "Prepare The Way Of The Lord | Lyric Video | Exalt Worship"
  },
  "sof1995-553": {
    "youtubeId": "LiyM59mV8cA",
    "videoTitle": "This is the day that the Lord has made   Lakewood Music  lyrics"
  },
  "sof1995-567": {
    "youtubeId": "527KHYeT75I",
    "videoTitle": "WE ARE HERE TO PRAISE YOU by Graham Kendrick-LYRICS"
  },
  "sof1995-569": {
    "youtubeId": "i2YEHMs05Lw",
    "videoTitle": "We Are Standing On Holy Ground Song Lyrics Video - Divine Hymns"
  },
  "sof1995-590": {
    "youtubeId": "-urMDHBcZvQ",
    "videoTitle": "We Will Glorify the King of Kings  - Lyrics Acapella"
  },
  "sof1995-607": {
    "youtubeId": "MDqGRJQcs1s",
    "videoTitle": "Who's on the Lord’s side (lyric video) by Rev. Timothy Wright"
  },
  "rs1900-11a": {
    "youtubeId": "Ad_wVF7z1PM",
    "videoTitle": "My Song Shall Be of Jesus  (244) Lyrics"
  },
  "rs1900-36": {
    "youtubeId": "Wq__VQjkgYk",
    "videoTitle": "We Praise Thee O God For The Son Of Thy Love(Revive Us Again) - Hymn Lyrics & Music"
  },
  "rs1900-45": {
    "youtubeId": "tA9RuNAv5ls",
    "videoTitle": "Let The Weary Rest By First Love Music Lyric Video"
  },
  "rs1900-81a": {
    "youtubeId": "enK7lb-9FNo",
    "videoTitle": "It Was For Me {with lyrics} - //D. Bolling, R. France\\\\ ++The Wilds Men's Quartet++"
  },
  "rs1900-152": {
    "youtubeId": "yUWXpRUkzw8",
    "videoTitle": "Art Thou Weary, Art Thou Languid? with lyrics"
  },
  "rs1900-269": {
    "youtubeId": "c6k6l1OFIb0",
    "videoTitle": "I Hear Thy Welcome Voice (With Lyrics) | Beautiful Hymn"
  },
  "rs1900-284a": {
    "youtubeId": "dUhOljmDNOU",
    "videoTitle": "My Life My Love I Give To Thee - Hymn Lyrics & Music"
  },
  "rs1900-305": {
    "youtubeId": "gQPFdP3_tpY",
    "videoTitle": "There's a Land That Is Fairer Than Day (Cree with Lyrics)"
  },
  "rs1900-312a": {
    "youtubeId": "vYuA-TIex30",
    "videoTitle": "Jesus, Thy Blood and Righteousness (organ & lyrics)"
  },
  "rs1900-330a": {
    "youtubeId": "2MnYSMrxJpk",
    "videoTitle": "JESUS SAVIOUR PILOT ME         KIDS SONG 🎵 LYRICS BY GLEN DE YOUNG"
  },
  "rs1900-339a": {
    "youtubeId": "ReOkHKkJLnc",
    "videoTitle": "True Hearted, Whole Hearted, Faithful And Loyal - Hymn Lyrics & Music"
  },
  "rs1900-357": {
    "youtubeId": "329mgZkCjcg",
    "videoTitle": "Come we that love the lord hymn with lyrics |Marching to Zion hymn with lyrics | SDA HYMNAL 422"
  },
  "curated-ws-121": {
    "youtubeId": "Merf00qcQik",
    "videoTitle": "All I Once Held Dear (Knowing You, Jesus) [with lyrics for congregations]"
  },
  "ccli-uk-39": {
    "youtubeId": "7PjSO5Ihl0M",
    "videoTitle": "Faithful One - Brian Doerksen [with lyrics]"
  },
  "ccli-uk-59": {
    "youtubeId": "bdWZlMhzKoQ",
    "videoTitle": "I Give You My Heart - The Worship Initiative (Lyrics)"
  },
  "ccli-uk-71": {
    "youtubeId": "qT6czqPgJ5s",
    "videoTitle": "Hillsong - This is our God (Lyrics)"
  },
  "ccli-uk-79": {
    "youtubeId": "xdeFFKRX8as",
    "videoTitle": "Worthy - Elevation Worship Lyric Video"
  },
  "ccli-uk-86": {
    "youtubeId": "C8k6jSS7sb4",
    "videoTitle": "I Thank God (lyrics)"
  },
  "curated-ws-185": {
    "youtubeId": "ZFQGc9p_F0I",
    "videoTitle": "He Will Hold Me Fast v2 | Matt Merker | #choir #lyrics"
  },
  "ws-66": {
    "youtubeId": "Tjz4yXUJrgU",
    "videoTitle": "Thine Be the Glory (Tune: Maccabeus - 3vv+refrain) [with lyrics for congregations]"
  },
  "ws-91": {
    "youtubeId": "RCLGIpmoGZs",
    "videoTitle": "All Things Bright and Beautiful (Tune: Monk - 5vv) [with lyrics for congregations]"
  },
  "curated-ws-116": {
    "youtubeId": "gipC9UQ0p5o",
    "videoTitle": "Spirit of the living God fall afresh on me      lyrics"
  },
  "curated-ws-127": {
    "youtubeId": "XDHAf1-cA0I",
    "videoTitle": "Open Our Eyes Lord with Lyrics: Author: Bob Cull. Singers: The Maranatha:"
  },
  "curated-ws-145": {
    "youtubeId": "oqG2jPXVc-A",
    "videoTitle": "Show your power (He is the Lord) - Lyric Video"
  },
  "artist-taize-3": {
    "youtubeId": "l8yOAxWyfvA",
    "videoTitle": "Veni Sancte Spiritus (Taizé) [with lyrics for congregations]"
  },
  "artist-taize-4": {
    "youtubeId": "-OHPoVhwgnM",
    "videoTitle": "Stay With Me (Taizé) [with lyrics for congregations]"
  },
  "artist-taize-6": {
    "youtubeId": "ZERr4Nc2gZE",
    "videoTitle": "Within our darkest night lyrics backing"
  },
  "broad-ishmael-8": {
    "youtubeId": "fyPaS2m4e5A",
    "videoTitle": "Lord We've Come To Worship - Paul Baloche - Worship Video with lyrics"
  },
  "am2013-33a": {
    "youtubeId": "bV2H_zRQL5s",
    "videoTitle": "Creator of the Starry Height - with lyrics"
  },
  "am2013-40": {
    "youtubeId": "qXKOxub5obc",
    "videoTitle": "Into The Darkness of This World (aka Come Lord Jesus Come) by Maggi Dawn - Lyric Video"
  },
  "am2013-52": {
    "youtubeId": "9sj0qShQazs",
    "videoTitle": "The People That In Darkness Sat Lyrics (Dundee) ALTO # Epiphany Hymns"
  },
  "am2013-87": {
    "youtubeId": "gzLzF6jyE1A",
    "videoTitle": "Thou Who Wast Rich Beyond All Splendor - Hymn Lyrics & Music"
  },
  "am2013-89b": {
    "youtubeId": "LmyZOCsoEHM",
    "videoTitle": "While Shepherds Watched Their Flocks By Night with Lyrics"
  },
  "am2013-117b": {
    "youtubeId": "aO_j16czYa8",
    "videoTitle": "COME LET US TO THE LORD OUR GOD Hymn Lyrics Words text trending sing along song music"
  },
  "am2013-136": {
    "youtubeId": "ZCKcSGvj_lQ",
    "videoTitle": "GOD OF OUR MOTHERS AND FATHERS [Official Lyric Video] | Feat. Samuel Lane | Vineyard Worship"
  },
  "am2013-138": {
    "youtubeId": "Y0D8rsb1Q8A",
    "videoTitle": "Father God in Heaven (Kumbaya - Lord's Prayer) [with lyrics for congregations]"
  },
  "am2013-148b": {
    "youtubeId": "C3WCHkN8_lA",
    "videoTitle": "Hymn - O Dearest Lord, Thy Sacred Head - Ayrshire - with words - Daniel Roberts | Organist"
  },
  "am2013-161b": {
    "youtubeId": "MD9rMkIS1yw",
    "videoTitle": "Ride on, Ride on in Majesty - WITH LYRICS"
  },
  "am2013-200b": {
    "youtubeId": "3LzVgBgocOs",
    "videoTitle": "Christ The Lord Is Risen Again Lyrics (Wurtemburg) # Easter Hymns"
  },
  "am2013-201b": {
    "youtubeId": "mqI_8gCb0ag",
    "videoTitle": "Come, ye faithful, raise the strain english christian hymn with lyrics"
  },
  "am2013-225": {
    "youtubeId": "M8xZi78KrUw",
    "videoTitle": "Clap Your Hands, All You Nations (Lyrics Video) | Worship Anthem by Global God Music"
  },
  "am2013-238b": {
    "youtubeId": "edK3Vv7Qwo4",
    "videoTitle": "Come Down O Love Divine (Tune: Down Ampney - 4vv) [with lyrics for congregations]"
  },
  "am2013-257": {
    "youtubeId": "fylsIaNsJ5o",
    "videoTitle": "Audrey Assad - Spirit of the living God [Lyrics]"
  },
  "am2013-278": {
    "youtubeId": "AoG-vb2NayE",
    "videoTitle": "We Give Immortal Praise [A Hymn to the Holy Trinity] -by Rev Adam [Christian Song with Lyrics] Music"
  },
  "am2013-279": {
    "youtubeId": "5iFvHkL5Qqs",
    "videoTitle": "Jesus on the Mountain Peak (Tune: Unknown - 4vv) [with lyrics for congregations]"
  },
  "am2013-284": {
    "youtubeId": "5CRW9qC2pqU",
    "videoTitle": "For the Fruits of all creation. Lyric video (StF 124)"
  },
  "am2013-286": {
    "youtubeId": "L2mfHD3h8gE",
    "videoTitle": "Praise, O Praise Our God and King - Hymn 117 - Lyric Video"
  },
  "am2013-302b": {
    "youtubeId": "UGUfIMDcicc",
    "videoTitle": "How Beauteous Are Their Feet(Watts) - Old Hymn Lyrics & Music"
  },
  "am2013-303b": {
    "youtubeId": "kjm7VJBDvcI",
    "videoTitle": "How Bright These Glorious Spirits Shine Lyrics (Bromsgrove) # All Saints Day Hymns"
  },
  "am2013-305": {
    "youtubeId": "VHwA7EhGRqY",
    "videoTitle": "Lo Round The Throne A Glorious Band Lyrics (Old 100th) # All Saints Day Hymns"
  },
  "am2013-320": {
    "youtubeId": "kAHMcm_Z0k0",
    "videoTitle": "THE GREAT FORERUNNER OF THE MORN Hymn Lyrics Words text trending sing along song music"
  },
  "am2013-344": {
    "youtubeId": "7FNTKcoYbW4",
    "videoTitle": "Come To A Wedding, Come To A Blessing Song Lyrics | Christian Wedding Song |  Divine Hymns"
  },
  "am2013-350": {
    "youtubeId": "Ua9GlERgoBY",
    "videoTitle": "We Pledge To One Another -  Hymn Lyrics & Music"
  },
  "am2013-369": {
    "youtubeId": "urPu2L6uMsk",
    "videoTitle": "Our Father Hear Our Prayer with lyrics"
  },
  "am2013-397": {
    "youtubeId": "TLAYJflLUmA",
    "videoTitle": "067 SDA Hymn - O Lord Now Let You Servant (Singing w/ Lyrics)"
  },
  "am2013-425": {
    "youtubeId": "O2k6p2HIip8",
    "videoTitle": "Be Known to Us in Breaking Bread (Lyrics)"
  },
  "am2013-436": {
    "youtubeId": "J4DixF0U608",
    "videoTitle": "Hymn - Christians, Lift Your Hearts And Voices - with words - Daniel Roberts | Organist"
  },
  "am2013-449b": {
    "youtubeId": "cyPOEjPCLYc",
    "videoTitle": "Hymn - I Hunger And I Thirst - with words - Daniel Roberts | Organist"
  },
  "am2013-454": {
    "youtubeId": "RA3tnbbLjtA",
    "videoTitle": "Love Is His Word | #choir #lyrics"
  },
  "am2013-456b": {
    "youtubeId": "YWxBJ2PmWQs",
    "videoTitle": "Christian Gospel Song #143  -  “Now Let Us From This Table Rise”  |  With Lyrics"
  },
  "am2013-459": {
    "youtubeId": "A_cLTsJSfzY",
    "videoTitle": "O FOOD TO PILGRIMS GIVEN Hymn Lyrics Words text trending sing along song music UMC 631 Methodist"
  },
  "am2013-467": {
    "youtubeId": "jaMWPSuLxro",
    "videoTitle": "411 SDA Hymnal - The Son Of God Proclaim (Singing w/ Lyrics)"
  },
  "am2013-468b": {
    "youtubeId": "kOeGKcyFvD4",
    "videoTitle": "Thee We Adore O Hidden Saviour Thee Lyrics(St.Sacrament) # Communion Hymns"
  },
  "am2013-477": {
    "youtubeId": "wudU2X9fFu0",
    "videoTitle": "Go forth and tell! O Church of God, awake! - Hymn Lyrics & Music"
  },
  "am2013-481": {
    "youtubeId": "6Rr1TaVRpDs",
    "videoTitle": "Send Me Lord (Lyric Video) - Matt Redmond"
  },
  "am2013-497": {
    "youtubeId": "2Z__U5_ktdw",
    "videoTitle": "Lord Of The Church, We Pray For Our Renewing Song Lyrics Video - Divine Hymns"
  },
  "am2013-498": {
    "youtubeId": "GnYUfhtz11Q",
    "videoTitle": "Lord your church on earth is seeking. Lyric video (Stf 410)"
  },
  "am2013-516": {
    "youtubeId": "vQ341cHZIVo",
    "videoTitle": "Jesus Christ is Lord of All - & Lyrics"
  },
  "am2013-537b": {
    "youtubeId": "Zy7t2Uasqe8",
    "videoTitle": "For the Beauty of the Earth (Michelle Swift, Hymn with Lyrics, Contemporary)"
  },
  "am2013-544a": {
    "youtubeId": "6P4WKUKUKW4",
    "videoTitle": "Morning Glory, Starlit Sky Hymn with Lyrics"
  },
  "am2013-549": {
    "youtubeId": "m3cN328bYwc",
    "videoTitle": "The heavens declare thy glory Lord! | Worship Song with Lyrics | Isaac Watts"
  },
  "am2013-563": {
    "youtubeId": "_CSzEviUc_o",
    "videoTitle": "Jesus Christ is Waiting (5vv) [with lyrics for congregations]"
  },
  "am2013-569b": {
    "youtubeId": "-BVemd2l4kw",
    "videoTitle": "The Kingdom of God is Justice and Joy Hymn lyrics"
  },
  "am2013-570": {
    "youtubeId": "3Dr0pd1Ao6E",
    "videoTitle": "To Christ The Prince Of Peace Lyrics (St George)"
  },
  "am2013-573": {
    "youtubeId": "ccVXF1ubBKo",
    "videoTitle": "Lord We Pray For Golden Peace - Christian Hymn - With lyrics"
  },
  "am2013-596": {
    "youtubeId": "ZkN9yHdSE5o",
    "videoTitle": "Because the Lord is my Shepherd, I have ev'rything that I need | The New 23rd (Psalm 23) With Lyrics"
  },
  "am2013-622": {
    "youtubeId": "3Rl9mevZOOc",
    "videoTitle": "Lord I Long To See Your Face w Lyrics"
  },
  "am2013-629b": {
    "youtubeId": "4iPjsvKLvZM",
    "videoTitle": "Father, Hear The Prayer We Offer - hymn with lyrics"
  },
  "am2013-640b": {
    "youtubeId": "qKfCf3D01d0",
    "videoTitle": "Give to Our God Immortal Praise (Tune: Duke Street - 5vv) [with lyrics for congregations]"
  },
  "am2013-651": {
    "youtubeId": "En6AqMII3OE",
    "videoTitle": "Great Shepherd Of Thy People Hear Lyrics (Oswalds Tree) # General Hymns"
  },
  "am2013-680": {
    "youtubeId": "zpEycHpPLM8",
    "videoTitle": "In Christ There is No East or West (Tune: Manchester - 3vv) [with lyrics for congregations]"
  },
  "am2013-682b": {
    "youtubeId": "TfZgP1c_6Js",
    "videoTitle": "In the Cross of Christ I Glory - Hymn Sing Along [Lyrics Onscreen]"
  },
  "am2013-687": {
    "youtubeId": "Ep8mB9Wlg2s",
    "videoTitle": "Jesus, Priceless Treasure Hymn with lyrics (Jesu, Meine Freude)"
  },
  "am2013-693": {
    "youtubeId": "_fzKdIF_Eys",
    "videoTitle": "Hymn - Jesus, Humble Was Your Birth - with words - Daniel Roberts | Organist"
  },
  "am2013-698b": {
    "youtubeId": "x-1MJTTeUD8",
    "videoTitle": "King Of Glory King Of Peace - song and lyrics"
  },
  "am2013-711b": {
    "youtubeId": "pwpkCte_g7c",
    "videoTitle": "Like a Mighty River Flowing - PTL 75 - Lyric Video"
  },
  "am2013-727b": {
    "youtubeId": "lEucuzzelmA",
    "videoTitle": "May the mind of Christ my Saviour [LYRIC VIDEO]"
  },
  "am2013-742b": {
    "youtubeId": "4O9kw3cILpg",
    "videoTitle": "O For A Thousand Tongues To Sing (Hymn with words and music) - Charles Wesley"
  },
  "am2013-753": {
    "youtubeId": "JFVVj5096Ok",
    "videoTitle": "O Praise Ye The Lord! Praise Him In The Height(Laudate Dominum) - Old Hymn Lyrics & Music"
  },
  "am2013-763b": {
    "youtubeId": "EVP6nQj1a_c",
    "videoTitle": "Praise to the Holiest in the Height (Tune: Richmond - 7vv) [with lyrics for congregations]"
  },
  "am2013-778b": {
    "youtubeId": "Vq-Lhkx4LaE",
    "videoTitle": "Sing praise to God who reigns above Lyrics SDA Hymnal 029"
  },
  "am2013-787b": {
    "youtubeId": "Of4l5bTdZ8M",
    "videoTitle": "Take My Life and Let it Be (Tune: Mozart/Nottingham - 6vv) [with lyrics for congregations]"
  },
  "am2013-794b": {
    "youtubeId": "WLdPoQnylnA",
    "videoTitle": "The King Of Love My Shepherd Is | Christian Hymn | Psalm 23 | Choir with Lyrics | Sunday 7pm Choir"
  },
  "am2013-816b": {
    "youtubeId": "T4cpL-r84pU",
    "videoTitle": "Thy Kingdom Come, O God - Hymn 285 - 1st Tune - Lyric Video"
  },
  "am2013-824": {
    "youtubeId": "uC1ESmzAlMw",
    "videoTitle": "With Joy We Meditate The Grace(Watts) -Hymn Lyrics & Music"
  },
  "am2013-832": {
    "youtubeId": "tZ3D36nh7bk",
    "videoTitle": "Calm Me Lord As You Calm The Storm + Church View- Lyrics on description"
  },
  "sof1995-7": {
    "youtubeId": "y_5CxG2R0_g",
    "videoTitle": "Bethel Music - All Hail King Jesus (with lyrics)(2021)"
  },
  "sof1995-26": {
    "youtubeId": "Y6XacIRPttk",
    "videoTitle": "Ascribe Greatness To Our God, The Rock Song Lyrics | Divine Hymns"
  }
};
